--===============
-- EDA Project
--===============

-------------------------
--database exploration
-------------------------

-- explore the objects

select * from INFORMATION_SCHEMA.TABLES;

--explore columns

select * from INFORMATION_SCHEMA.columns;

----------------------------------
--dimensions exploration
----------------------------------

--explore the countries our customers come from

select distinct
	country
from gold.dim_customers

--explore all product category

select distinct
	category
from gold.dim_products


select distinct
	subcategory
from gold.dim_products


select distinct
	product_name
from gold.dim_products

----------------------------------------
--date exploration
----------------------------------------

select
	min(order_date) as first_order_date,
	max(order_date) as last_order_date,
	datediff(year,min(order_date),max(order_date)) as the_order_years
from gold.fact_sales;


--the yougest and oldest ages

select
	min(birth_date) oldest_bdate,
	datediff(year,min(birth_date),getdate()) oldest_age,
	max(birth_date) yougest_bdate,
	datediff(year,max(birth_Date),getdate()) yougest_age
from gold.dim_customers

----------------------------------
--measures exploration
----------------------------------
--calculate the key metrics of the business "Big Numbers"

select 'Total_Sales' as measure_name, sum(sales_amount) as measure_value from gold.fact_sales
union all
select 'Total_Orders' as measure_name, count(distinct order_number) as measure_value from gold.fact_sales
union all
select 'Total_Customers' as measure_name, count(distinct customer_key) as measure_value from gold.dim_customers
union all
select 'Total_customers_placed_orders' as measure_name, count(distinct customer_key) as measure_value from gold.fact_sales
union all
select 'Total_products' as measure_name, count(distinct product_key) as measure_value from gold.dim_products
union all
select 'Total_Quantity' as measure_name, sum(quantity) as measure_value from gold.fact_sales
union all
select 'Average_Price' as measure_name, avg(price) as measure_value from gold.fact_sales

--------------------------
--magnitude exploration
--------------------------

--find total customers by country

select
	country,
	count(distinct customer_key) total_customers
from gold.dim_customers
group by country

--find total customers by gender

select
	gender,
	count(distinct customer_key) total_customers
from gold.dim_customers
group by gender

--find total products by category

select
	category,
	count(distinct product_key)
from gold.dim_products
group by category

--what's the average cost in each category

select
	category,
	avg(cost)
from gold.dim_products
group by category

--what's the total revenue generated for each category?

select
	category,
	sum(sales_amount) total_sales
from gold.fact_sales f
left join  gold.dim_products p
on f.product_key = p.product_key
group by category

--find total revenue is generated by each customer

select
	c.customer_key,
	c.first_name,
	c.last_name,
	sum(sales_amount) total_sales
from gold.fact_sales f
left join  gold.dim_customers c
on c.customer_key = f.customer_key
group by c.customer_key,c.first_name,c.last_name

--what's the distribution of sold items across countries?

select
	country,
	sum(quantity) as no_sold_items
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
where country != 'n/a'
group by country

---------------------------------
--Ranking "Top N / Bottom N"
---------------------------------

--which 5 products generate the highest revenue?

--using TOP
select top 5
	product_name,
	sum(sales_amount) total_revenue
from gold.fact_sales f
left join gold.dim_products p
on f.product_key = p.product_key
group by product_name
order by total_revenue desc;


--using WINDOW FUN.
select
	product_name,
	total_revenue
from(
	select
		product_name,
		sum(sales_amount) total_revenue,
		row_number() over(order by sum(sales_amount) desc) ranking
	from gold.fact_sales f
	left join gold.dim_products p
	on f.product_key = p.product_key
	group by product_name)t
where ranking <= 5;



--what are the 5 worst performing products in terms of sales?

select top 5
	product_name,
	sum(sales_amount) total_revenue
from gold.fact_sales f
left join gold.dim_products p
on f.product_key = p.product_key
group by product_name
order by total_revenue asc;


--the 3 customers with the fewest orders placed

select top 3 with ties
	c.customer_key,
	first_name,
	last_name,
	count(order_number) as total_orders
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by c.customer_key, first_name,last_name
order by total_orders asc;
